#!/usr/bin/env python3
"""Batch translate descriptions in core docs"""
import re, json
from pathlib import Path

docs = Path('website/docs')

desc_map = {
  "How the ACP adapter works: lifecycle, sessions, event bridge, approvals, and too": "ACP 适配器的工作原理：生命周期、会话管理、事件桥接、审批流程和工具渲染",
  "How to add a new inference provider to OpenClaw — auth, runtime resolution, CLI ": "如何为 OpenClaw 添加新的推理提供商 — 认证、运行时解析和 CLI 集成",
  "How to add a new tool to OpenClaw — schemas, handlers, registration, and toolset": "如何为 OpenClaw 添加新工具 — 模式、处理器、注册和工具集管理",
  "Detailed walkthrough of AIAgent execution, API modes, tools, callbacks, and fall": "AIAgent 执行流程详解：API 模式、工具调用、回调和回退机制",
  "OpenClaw internals — major subsystems, execution paths, data flow, and where to ": "OpenClaw 内部架构 — 主要子系统、执行路径、数据流向及代码位置",
  "How OpenClaw detects and responds to native JS dialogs and interacts with cross-": "OpenClaw 如何检测和响应原生 JS 对话框并与跨域 iframe 交互",
  "How to build a context engine plugin that replaces the built-in ContextCompresso": "如何构建替换内置 ContextCompressor 的上下文引擎插件",
  "How to contribute to OpenClaw — dev setup, code style, PR process": "如何为 OpenClaw 贡献代码 — 开发环境搭建、代码规范、PR 流程",
  "How to create skills for OpenClaw — SKILL.md format, guidelines, and publishing": "如何为 OpenClaw 创建技能 — SKILL.md 格式、编写指南和发布流程",
  "How OpenClaw stores, schedules, edits, pauses, skill-loads, and delivers cron jo": "OpenClaw 如何存储、调度、编辑、暂停、加载技能和投递定时任务",
  "Build wrapper CLIs that extend the OpenClaw TUI with custom widgets, keybindings": "构建可扩展 OpenClaw TUI 的包装器 CLI，支持自定义组件、快捷键和面板布局",
  "How the messaging gateway boots, authorizes users, routes sessions, and delivers": "消息网关如何启动、认证用户、路由会话和投递消息",
  "How to build an image-generation backend plugin for OpenClaw": "如何为 OpenClaw 构建图像生成后端插件",
  "How to build a memory provider plugin for OpenClaw": "如何为 OpenClaw 构建记忆提供商插件",
  "How to build a model provider (inference backend) plugin for OpenClaw": "如何为 OpenClaw 构建模型提供商（推理后端）插件",
  "Run any LLM call from inside a plugin via ctx.llm — chat or structured, sync or ": "从插件内部通过 ctx.llm 调用任意 LLM — 对话或结构化输出，同步或异步",
  "Three protocols for driving openclaw from external programs: ACP, the TUI gatewa": "从外部程序驱动 OpenClaw 的三种协议：ACP、TUI 网关和 API 服务器",
  "How OpenClaw builds the system prompt, preserves cache stability, and injects ep": "OpenClaw 如何构建系统提示词、保持缓存稳定性和注入临时内容",
  "How OpenClaw resolves providers, credentials, API modes, and auxiliary models at": "OpenClaw 如何在运行时解析提供商、凭证、API 模式和辅助模型",
  "Runtime behavior of the tool registry, toolsets, dispatch, and terminal environm": "工具注册表、工具集、调度和终端环境的运行时行为",
  "How to build a video-generation backend plugin for OpenClaw": "如何为 OpenClaw 构建视频生成后端插件",
  "How to build a web-search/extract/crawl backend plugin for OpenClaw": "如何为 OpenClaw 构建网页搜索/提取/爬取后端插件",
  "Install OpenClaw on Linux, macOS, WSL2, native Windows, or Android via Termux": "在 Linux、macOS、WSL2、Windows 原生或 Android Termux 上安装 OpenClaw",
  "Install and deploy OpenClaw with Nix — from quick `nix run` to fully declarative": "使用 Nix 安装和部署 OpenClaw — 从快速运行到完全声明式配置",
  "Your first conversation with OpenClaw — from install to chatting in under 5 minu": "你的第一次 OpenClaw 对话 — 5 分钟内完成安装并开始聊天",
  "Run OpenClaw directly on an Android phone with Termux": "在 Android 手机上通过 Termux 直接运行 OpenClaw",
  "How to update OpenClaw to the latest version or uninstall it": "如何更新 OpenClaw 到最新版本或卸载",
  "Real-world automation patterns using OpenClaw cron — monitoring, reports, pipeli": "使用 OpenClaw cron 的实战自动化模式 — 监控、报告、数据管道和告警",
  "Ready-to-use automation blueprints — scheduled tasks, GitHub event triggers, API": "即用型自动化蓝图 — 定时任务、GitHub 事件触发器和 Webhook 集成",
  "Use OpenClaw with Amazon Bedrock — native Converse API, IAM authentication, Guar": "在 Amazon Bedrock 上使用 OpenClaw — 原生 Converse API、IAM 认证和防护",
  "Use OpenClaw with Microsoft Foundry — OpenAI-style and Anthropic-style endpoints": "在 Microsoft Foundry (Azure) 上使用 OpenClaw — 兼容 OpenAI 和 Anthropic 接口",
  "When and how to use subagent delegation — patterns for parallel research, code r": "何时以及如何使用子代理委派 — 并行研究、代码审查和多工作流模式",
  "Use OpenClaw with Google Gemini — native AI Studio API, API-key setup, tool call": "在 Google Gemini 上使用 OpenClaw — 原生 AI Studio API、API Key 设置和工具调用",
  "Step-by-step guide to running OpenClaw entirely on your own machine with Ollama ": "在本地机器上使用 Ollama 完整运行 OpenClaw 的分步指南 — 零 API 成本",
  "Azure portal walkthrough for creating the app registration that powers the Teams": "Azure 门户应用注册教程 — 为 Teams 会议总结管道提供支持",
  "Log into MiniMax via browser OAuth and use MiniMax-M2.7 models in OpenClaw — no ": "通过浏览器 OAuth 登录 MiniMax，在 OpenClaw 中使用 MiniMax-M2.7 模型",
  "How to complete browser-based OAuth (xAI, Spotify, MCP servers) when OpenClaw ru": "当 OpenClaw 运行在 SSH/远程主机上时如何完成基于浏览器的 OAuth 认证",
  "Runbook, go-live checklist, and operator worksheet for the Microsoft Teams meeti": "Microsoft Teams 会议管道的手册、上线清单和运维工作表",
  "Step-by-step guide to setting up a Telegram bot that your whole team can use for": "设置团队 Telegram 助手的完整指南",
  "Practical advice to get the most out of OpenClaw — prompt tips, CLI shortcuts, c": "充分利用 OpenClaw 的实用建议 — 提示技巧、CLI 快捷键和配置要点",
  "A practical guide to connecting MCP servers to OpenClaw, filtering their tools, ": "将 MCP 服务器连接到 OpenClaw 的实用指南 — 工具过滤和安全管理",
  "How to use SOUL.md to shape OpenClaw的 default voice, what belongs there, and how": "如何使用 SOUL.md 塑造 OpenClaw 的默认人格，哪些内容适合放入其中",
  "A practical guide to setting up and using OpenClaw voice mode across CLI, Telegr": "在 CLI、Telegram 和 Discord 上设置和使用 OpenClaw 语音模式的实用指南",
  "Find, install, use, and create skills — on-demand knowledge that teaches OpenCla": "查找、安装、使用和创建技能 — 让 OpenClaw 按需学习新知识的技能系统",
  "Sign in with your SuperGrok or X Premium+ subscription to use Grok models in Ope": "使用 SuperGrok 或 X Premium+ 订阅登录，在 OpenClaw 中使用 Grok 模型",
  "One subscription, 300+ frontier models, the Tool Gateway, and Nous Chat — the re": "一个订阅、300+ 前沿模型、工具网关和 Nous Chat — Nous Portal 的全部功能",
  "Reference for OpenClaw MCP configuration keys, filtering semantics, and utility-": "OpenClaw MCP 配置参考 — 配置键、过滤语义和实用工具",
  "Catalog of bundled skills that ship with OpenClaw": "OpenClaw 内置技能目录",
  "Complete reference for interactive CLI and messaging slash commands": "交互式 CLI 和消息斜杠命令完整参考",
  "Authoritative reference for OpenClaw built-in tools, grouped by toolset": "OpenClaw 内置工具权威参考，按工具集分组",
  "Reference for OpenClaw core, composite, platform, and dynamic toolsets": "OpenClaw 核心、复合、平台和动态工具集参考",
  "Authoritative reference for OpenClaw terminal commands and command families": "OpenClaw 终端命令和命令族的权威参考",
  "Complete reference of all environment variables used by OpenClaw": "OpenClaw 使用的所有环境变量完整参考",
  "Frequently asked questions and solutions to common issues with OpenClaw": "常见问题解答和 OpenClaw 故障解决方法",
  "Master the OpenClaw terminal interface — commands, keybindings, personalities, a": "掌握 OpenClaw 终端界面 — 命令、快捷键、人格和分屏操作",
  "Configure OpenClaw — config.yaml, providers, models, API keys, and more": "配置 OpenClaw — config.yaml、提供商、模型、API Key 等",
  "The native OpenClaw desktop app — a polished experience for chatting with OpenCl": "OpenClaw 原生桌面应用 — 更精致的聊天和工作体验",
  "Running OpenClaw in Docker and using Docker as a terminal backend": "在 Docker 中运行 OpenClaw 并使用 Docker 作为终端后端",
  "Use OpenClaw inside ACP-compatible editors such as VS Code, Zed, and JetBrains": "在 VS Code、Zed 和 JetBrains 等 ACP 兼容编辑器中使用 OpenClaw",
  "Expose openclaw as an OpenAI-compatible API for any frontend": "将 OpenClaw 暴露为 OpenAI 兼容 API，供任意前端使用",
  "Generate agent trajectories at scale — parallel processing, checkpointing, and t": "大规模生成代理轨迹 — 并行处理、检查点和轨迹调试",
  "Plugins shipped with OpenClaw that run automatically via lifecycle hooks — disk-": "随 OpenClaw 内置的自动运行插件 — 磁盘监控、文件清理等",
  "Programmatic Python execution with RPC tool access — collapse multi-step workflo": "通过 RPC 工具访问进行编程式 Python 执行 — 将多步骤工作流简化为单次调用",
  "Project context files — .hermes.md, AGENTS.md, CLAUDE.md, global SOUL.md, and .c": "项目上下文文件 — .hermes.md、AGENTS.md、CLAUDE.md、全局 SOUL.md 等",
  "Inline @-syntax for attaching files, folders, git diffs, and URLs directly into ": "使用 @ 语法将文件、文件夹、Git 差异和 URL 直接注入对话上下文",
  "Schedule automated tasks with natural language, manage them with one cron tool, ": "用自然语言调度自动化任务，通过一个 cron 工具管理全部定时作业",
  "Background maintenance for agent-created skills — usage tracking, staleness, arc": "对代理创建的技能进行后台维护 — 使用追踪、过期检测和归档清理",
  "Spawn isolated child agents for parallel workstreams with delegate_task": "通过 delegate_task 生成隔离的子代理，处理并行工作流",
  "Build themes and plugins for the OpenClaw web dashboard — palettes, typography, ": "为 OpenClaw Web 仪表板构建主题和插件 — 调色板、排版和小部件系统",
  "Set a standing goal and let OpenClaw keep working across turns until it's done. ": "设置持久化目标，让 OpenClaw 跨多轮对话持续工作直至完成",
  "AI-native persistent memory via Honcho — dialectic reasoning, multi-agent user m": "通过 Honcho 实现 AI 原生持久化记忆 — 辩证推理、多代理用户建模",
  "Run custom code at key lifecycle points — log activity, send alerts, post to web": "在关键生命周期节点运行自定义代码 — 日志记录、发送告警、发布到 Webhook",
  "Durable SQLite-backed task board for coordinating multiple OpenClaw profiles": "基于 SQLite 的持久化任务看板，用于协调多个 OpenClaw 配置",
  "Real language servers (pyright, gopls, rust-analyzer, …) wired into the post-wri": "将真实语言服务器（pyright、gopls、rust-analyzer 等）接入写入后检查流程",
  "Connect OpenClaw to external tool servers via MCP — and control exactly which MC": "通过 MCP 将 OpenClaw 连接到外部工具服务器，精确控制可用工具",
  "External memory provider plugins — Honcho, OpenViking, Mem0, Hindsight, Holograp": "外部记忆提供商插件 — Honcho、OpenViking、Mem0、Hindsight 等",
  "How OpenClaw remembers across sessions — MEMORY.md, USER.md, and session search": "OpenClaw 如何跨会话记忆 — MEMORY.md、USER.md 和会话搜索",
  "Customize OpenClaw的 personality with a global SOUL.md, built-in personalities, a": "通过全局 SOUL.md、内置人格和可叠加人格文件自定义 OpenClaw 人格",
  "Adopt an animated mascot that reacts to agent activity across the CLI, TUI, and ": "领养一个动画宠物，在 CLI、TUI 和 Web 上对代理活动做出实时反应",
  "Extend OpenClaw with custom tools, hooks, and integrations via the plugin system": "通过插件系统扩展 OpenClaw — 自定义工具、钩子和第三方集成",
  "On-demand knowledge documents — progressive disclosure, agent-managed skills, an": "按需加载的知识文档 — 渐进式展示、代理管理技能和自动技能发现",
  "Customize the Hermes CLI with built-in and user-defined skins": "使用内置和用户自定义皮肤个性化 OpenClaw CLI 外观",
  "Use your Nous Portal subscription (or other OAuth provider) as an OpenAI-compati": "将 Nous Portal 订阅（或其他 OAuth 提供商）作为 OpenAI 兼容 API 使用",
  "One subscription, every tool. Web search, image generation, TTS, and cloud brows": "一个订阅，全部工具。网页搜索、图像生成、TTS 和云端浏览器",
  "Overview of OpenClaw的 tools — what's available, how toolsets work, and terminal ": "OpenClaw 工具概览 — 可用工具、工具集工作原理和终端环境集成",
  "Text-to-speech and voice message transcription across all platforms": "跨所有平台的文字转语音和语音消息转文字",
  "Real-time voice conversations with OpenClaw — CLI, Telegram, Discord (DMs, text ": "与 OpenClaw 进行实时语音对话 — CLI、Telegram、Discord",
  "Browser-based administration panel for managing configuration, API keys, MCP ser": "基于浏览器的管理面板 — 管理配置、API Key、MCP 服务器和技能",
  "Filesystem safety nets for destructive operations using shadow git repos and aut": "使用影子 Git 仓库和自动提交的文件系统安全网，防止破坏性操作",
  "Set up OpenClaw as a DingTalk chatbot": "将 OpenClaw 设置为钉钉机器人",
  "Set up OpenClaw as a Discord bot": "将 OpenClaw 设置为 Discord 机器人",
  "Set up OpenClaw as an email assistant via IMAP/SMTP": "通过 IMAP/SMTP 将 OpenClaw 设置为邮件助手",
  "Set up OpenClaw as a Feishu or Lark bot": "将 OpenClaw 设置为飞书/Lark 机器人",
  "Set up OpenClaw as a Google Chat bot using Cloud Pub/Sub": "使用 Cloud Pub/Sub 将 OpenClaw 设置为 Google Chat 机器人",
  "Chat with OpenClaw from Telegram, Discord, Slack, WhatsApp, Signal, SMS, Email, ": "在 Telegram、Discord、Slack、WhatsApp、Signal、短信、邮件等平台上与 OpenClaw 对话",
  "Set up OpenClaw as a LINE Messaging API bot": "将 OpenClaw 设置为 LINE 消息 API 机器人",
  "Set up OpenClaw as a Matrix bot": "将 OpenClaw 设置为 Matrix 机器人",
  "Set up OpenClaw as a Mattermost bot": "将 OpenClaw 设置为 Mattermost 机器人",
  "Connect Open WebUI to OpenClaw via the OpenAI-compatible API server": "通过 OpenAI 兼容 API 服务器将 Open WebUI 连接到 OpenClaw",
  "Connect OpenClaw to Raft as an external agent via wake-channel bridge": "通过唤醒通道桥将 OpenClaw 连接到 Raft 作为外部代理",
  "Set up OpenClaw as a Signal messenger bot via signal-cli daemon": "通过 signal-cli 守护进程将 OpenClaw 设置为 Signal 机器人",
  "Set up OpenClaw as a Slack bot using Socket Mode": "使用 Socket Mode 将 OpenClaw 设置为 Slack 机器人",
  "Set up OpenClaw as an SMS chatbot via Twilio": "通过 Twilio 将 OpenClaw 设置为短信聊天机器人",
  "Set up the Microsoft Teams meeting summary pipeline with Microsoft Graph webhook": "使用 Microsoft Graph Webhook 设置 Teams 会议总结管道",
  "Set up OpenClaw as a Microsoft Teams bot": "将 OpenClaw 设置为 Microsoft Teams 机器人",
  "Set up OpenClaw as a Telegram bot": "将 OpenClaw 设置为 Telegram 机器人",
  "Receive events from GitHub, GitLab, and other services to trigger OpenClaw agent": "接收 GitHub、GitLab 等服务的事件，触发 OpenClaw 代理执行",
  "Connect OpenClaw to WeCom via the AI Bot WebSocket gateway": "通过 AI 机器人 WebSocket 网关将 OpenClaw 连接到企业微信",
  "Connect OpenClaw to personal WeChat accounts via the iLink Bot API": "通过 iLink Bot API 将 OpenClaw 连接到个人微信账号",
  "Set up OpenClaw as a WhatsApp bot via Meta's official Business Cloud API": "通过 Meta 官方 Business Cloud API 将 OpenClaw 设置为 WhatsApp 机器人",
  "Set up OpenClaw as a WhatsApp bot via the built-in Baileys bridge": "通过内置 Baileys 桥接将 OpenClaw 设置为 WhatsApp 机器人",
  "Connect OpenClaw to the Yuanbao enterprise messaging platform via WebSocket gate": "通过 WebSocket 网关将 OpenClaw 连接到元宝企业消息平台",
  "Security model, dangerous command approval, user authorization, container isolat": "安全模型、危险命令审批、用户授权、容器隔离和权限管理",
  "Session persistence, resume, search, management, and per-platform session tracki": "会话持久化、恢复、搜索、管理以及按平台的会话追踪",
  "Autonomous research assistant with arXiv and web tools": "带 arXiv 和网络工具功能的自主研究助手",
  "Run multiple OpenClaw agents safely on the same repository using git worktrees a": "使用 Git Worktrees 和 Docker 在同一仓库上安全运行多个 OpenClaw 代理",
  "Administrator-pinned, user-immutable config and secrets via a system-level manag": "通过系统级管理作用域实现管理员锁定、用户不可更改的配置和密钥",
  "Receive Microsoft Graph change notifications (meetings, calendar, chat, etc.) in": "在 OpenClaw 中接收 Microsoft Graph 变更通知（会议、日历、聊天等）",
  "Connect OpenClaw to personal WeChat accounts via the iLink Bot API": "通过 iLink Bot API 将 OpenClaw 连接到个人微信",
}

count = 0
for f in sorted(docs.rglob('*.md')):
    content = f.read_text(encoding='utf-8')
    m = re.search(r'^description:\s*"(.+)"', content, re.MULTILINE)
    if not m:
        continue
    old_desc = m.group(1)
    if old_desc in desc_map:
        new_desc = desc_map[old_desc]
        content = content.replace(f'description: "{old_desc}"', f'description: "{new_desc}"', 1)
        f.write_text(content, encoding='utf-8')
        count += 1
        print(f'  ✅ {f.relative_to(docs)}')

print(f'\n已翻译描述: {count}')
