#!/usr/bin/env python3
"""Batch translate markdown h1 titles"""
import re, json
from pathlib import Path

docs = Path('website/docs')

title_map = json.loads(r'''
{
  "Quickstart": "快速入门",
  "Nix & NixOS Setup": "Nix / NixOS 安装",
  "Android 上的 OpenClaw 与 Termux": "Android — Termux 安装",
  "CLI Interface": "CLI 界面",
  "Configuration": "配置指南",
  "Configuring Models": "模型配置",
  "Desktop App": "桌面应用",
  "Windows (Native) Guide": "Windows 原生安装",
  "Windows (WSL2) Guide": "WSL2 安装指南",
  "TUI": "TUI 终端界面",
  "Sessions": "会话管理",
  "Security": "安全",
  "API Server": "API 服务器",
  "Browser Automation": "浏览器自动化",
  "Built-in Plugins": "内置插件",
  "Codex App-Server Runtime": "Codex 应用服务器运行时",
  "Computer Use": "计算机使用 (Computer Use)",
  "Scheduled Tasks (Cron)": "定时任务 (Cron)",
  "Curator": "策展人 (Curator)",
  "Subagent Delegation": "子代理委派",
  "Extending the Dashboard": "扩展仪表板",
  "Fallback Providers": "备用提供商",
  "Honcho Memory": "Honcho 记忆",
  "Event Hooks": "事件钩子 (Hooks)",
  "Kanban tutorial": "看板教程",
  "Kanban — Multi-Agent Profile Collaboration": "看板 — 多代理协作",
  "MCP (Model Context Protocol)": "MCP (模型上下文协议)",
  "Memory Providers": "记忆提供商",
  "Persistent Memory": "持久化记忆",
  "Plugins": "插件系统",
  "Skills System": "技能系统",
  "Spotify": "Spotify 集成",
  "Voice & TTS": "语音与 TTS",
  "Voice Mode": "语音模式",
  "Web Dashboard": "Web 仪表板",
  "Web Search & Extract": "网络搜索与提取",
  "Messaging Gateway": "消息网关",
  "Discord Setup": "Discord 配置",
  "Feishu / Lark Setup": "飞书 / Lark 配置",
  "Google Chat Setup": "Google Chat 配置",
  "Matrix Setup": "Matrix 配置",
  "Slack Setup": "Slack 配置",
  "Telegram Setup": "Telegram 配置",
  "Webhooks": "Webhooks",
  "Weixin (WeChat)": "微信 (WeChat)",
  "WhatsApp Business Cloud API Setup": "WhatsApp Business Cloud API 配置",
  "WhatsApp 设置": "WhatsApp 设置",
  "Microsoft Graph Webhook 监听器": "Microsoft Graph Webhook 监听器",
  "Microsoft Teams 会议": "Microsoft Teams 会议",
  "Open WebUI Integration": "Open WebUI 集成",
  "蓝色泡泡 (iMessage)": "蓝色泡泡 (iMessage)",
  "光子 iMessage": "光子 iMessage",
  "SimpleX 聊天": "SimpleX 聊天",
  "Running Many Gateways at Once": "同时运行多个网关",
  "Profile Distributions: Share a Whole Agent": "配置分发：分享整个代理",
  "Multi Profile Gateways": "多配置网关",
  "Profiles": "配置文件",
  "Adding a Platform Adapter": "添加平台适配器",
  "Adding Providers": "添加提供商",
  "Architecture": "架构",
  "Context Compression and Caching": "上下文压缩与缓存",
  "Creating Skills": "创建技能",
  "Gateway Internals": "网关内部结构",
  "Building a Model Provider Plugin": "构建模型提供商插件",
  "Plugin LLM Access": "插件 LLM 访问",
  "Automation Blueprints": "自动化蓝图",
  "Microsoft Foundry": "Microsoft Foundry (Azure)",
  "Set Up a Team Telegram Assistant": "设置团队 Telegram 助手",
  "Use MCP with OpenClaw": "将 MCP 与 OpenClaw 配合使用",
  "xAI Grok OAuth (SuperGrok / X Premium+)": "xAI Grok OAuth",
  "Nous Portal": "Nous Portal",
  "AI Providers": "AI 提供商",
  "Claude Code": "Claude Code 技能",
  "ASCII 艺术": "ASCII 艺术",
  "Ascii Video": "ASCII 视频",
  "Claude Design": "Claude Design",
  "Comfyui": "ComfyUI",
  "Excalidraw": "Excalidraw",
  "Humanizer": "Humanizer",
  "P5Js": "p5.js",
  "Pretext": "Pretext",
  "Touchdesigner Mcp": "TouchDesigner MCP",
  "Jupyter Live 内核": "Jupyter Live 内核",
  "Github 授权": "GitHub 授权",
  "Github Code Review": "GitHub 代码审查",
  "Github 问题": "GitHub 问题",
  "Github Repo Management": "GitHub 仓库管理",
  "YouTube 内容": "YouTube 内容处理",
  "Evaluating Llms Harness": "LLM 评估平台",
  "Weights And Biases": "Weights & Biases",
  "Audiocraft Audio Generation": "Audiocraft 音频生成",
  "Segment Anything Model": "Segment Anything 模型",
  "Google Workspace": "Google Workspace",
  "Notion": "Notion",
  "Arxiv": "arXiv 论文搜索",
  "Blogwatcher": "Blogwatcher",
  "Llm Wiki": "LLM Wiki",
  "Research Paper Writing": "学术论文写作",
  "Xurl": "Xurl",
  "Python Debugpy": "Python Debugpy",
  "Yuanbao": "元宝",
  "Google Workspace 技能": "Google Workspace 技能",
  "Grok": "Grok",
  "Honcho": "Honcho",
  "OpenHands CLI": "OpenHands CLI",
  "Baoyu Comic": "宝娱漫画",
  "Concept Diagrams": "概念图",
  "Hyperframes": "Hyperframes",
  "推理 Sh Cli": "推理 CLI",
  "Docker 管理": "Docker 管理",
  "Pinggy Tunnel": "Pinggy Tunnel",
  "3 Statement Model": "三表模型",
  "Comps Analysis": "可比公司分析",
  "Dcf Model": "DCF 估值模型",
  "Excel 作者": "Excel 写作",
  "Lbo Model": "LBO 模型",
  "Pptx 作者": "PPT 写作",
  "Neuroskill Bci": "Neuroskill BCI",
  "Openclaw Migration": "OpenClaw 迁移",
  "Guidance": "Guidance",
  "Huggingface Tokenizers": "HuggingFace Tokenizers",
  "Outlines": "Outlines",
  "Instructor": "Instructor",
  "Lambda Labs Gpu Cloud": "Lambda Labs GPU 云",
  "Obliteratus": "Obliteratus",
  "Peft Fine Tuning": "PEFT 微调",
  "Pytorch Fsdp": "PyTorch FSDP",
  "Pytorch 闪电": "PyTorch Lightning",
  "Qdrant Vector Search": "Qdrant 向量搜索",
  "Dspy": "DSPy",
  "Sparse Autoencoder Training": "稀疏自编码器训练",
  "Slime Rl Training": "Slime RL 训练",
  "Stable Diffusion Image Generation": "Stable Diffusion 图像生成",
  "Tensorrt Llm": "TensorRT-LLM",
  "分布式 LLM 预训练 Torchtitan": "分布式 LLM 预训练 (Torchtitan)",
  "Fine Tuning With Trl": "TRL 微调",
  "Stripe 链接 CLI": "Stripe 链接 CLI",
  "Memento Flashcards": "Memento 闪卡",
  "Shop": "Shop",
  "Shopify": "Shopify",
  "Telephony": "Telephony",
  "Bioinformatics": "生物信息学",
  "Duckduckgo 搜索": "DuckDuckGo 搜索",
  "Gitnexus 浏览器": "GitNexus 浏览器",
  "Qmd": "Qmd",
  "SearXNG 搜索": "SearXNG 搜索",
  "macOS": "1Password",
  "Godmode": "Godmode",
  "Oss Forensics": "OSS 取证",
  "Code Wiki": "Code Wiki",
  "Rest Graphql Debug": "REST/GraphQL 调试",
  "CLI Commands Reference": "CLI 命令参考",
  "Environment Variables Reference": "环境变量参考",
  "FAQ & Troubleshooting": "常见问题与故障排查",
  "Optional Skills Catalog": "可选技能目录",
  "Profile Commands Reference": "配置命令参考",
  "Bundled Skills Catalog": "内置技能目录",
  "Slash Commands Reference": "斜杠命令参考",
  "Built-in Tools Reference": "内置工具参考",
  "Git Worktrees": "Git Worktrees",
  "Checkpoints And Rollback": "检查点与回滚",
  "Managed Scope": "托管作用域",
  "X (Twitter) 搜索": "X (Twitter) 搜索",
  "看板 Codex Lane": "看板 Codex Lane 技能"
}
''')

count = 0
unmatched = []
for f in sorted(docs.rglob('*.md')):
    content = f.read_text(encoding='utf-8')
    m = re.search(r'^#\s+(.+)$', content, re.MULTILINE)
    if not m:
        continue
    old_title = m.group(1).strip()
    if old_title in title_map:
        new_title = title_map[old_title]
        content = content.replace(f'# {old_title}', f'# {new_title}', 1)
        f.write_text(content, encoding='utf-8')
        count += 1
        print(f'  {f.relative_to(docs)}')
    else:
        cn_chars = sum(1 for c in old_title if '\u4e00' <= c <= '\u9fff')
        if cn_chars >= len(old_title.strip()) * 0.3:
            continue
        unmatched.append((f.relative_to(docs), old_title))

print(f'\n=== 结果 ===')
print(f'已翻译: {count}')
print(f'仍英文未匹配: {len(unmatched)}')
for f, t in unmatched:
    print(f'  {f}: "{t}"')
